### ISSUE TITLE
Add public key token to Flurl

### ISSUE THREAD

**Issue by AleyCZ** [tmenier/Flurl#665] opened 2022-01-20 12:33 UTC
Please add public key token to Flurl. Without it, we are facing strange issues in some projects.

What is happening: We do not use Flurl directly, we use other nugets and they use Flurl. Apparently, some 3rd party nugets reference some versions of Flurl in their nuspec, but then a different version of Flurl is required by their csproj so there is a Flurl version mismatch in runtime. And this issue is not visible anywhere, it does not produce neither compilation warning nor error message in runtime.

I think this is because Flurl has no public key token. Without it, .NET runtime takes just any version and uses it without any warning or anything. And crazy things happen if there are some incompatibilities. For example in our case we need 2.8.0, but .NET compiler put there 2.5.0 instead. Silently. Because this is not an issue for it due to missing public key token.

I am also going to ask authors of other nugets to fix their dependencies. Of course. But I think the root cause is here - if there was a public key token in Flurl, its users would see compilation or runtime messages and fixed their nugets.

**Comment by tmenier** [comment] 2022-01-20 13:48
Not a bug. You're asking for a signed package, which I don't provide but others have. I don't think there's currently a maintainer of the signed packages, but please feel free to volunteer: https://github.com/tmenier/Flurl/issues/39

**Comment by tmenier** [comment] 2022-01-20 13:52
Actually, I take it back, they are up to date. I didn't think they were but it turns out you're in luck! :)

https://www.nuget.org/packages/Flurl.Http.Signed
https://www.nuget.org/packages/Flurl.Signed

**Comment by tmenier** [comment] 2022-01-22 15:29
Closing as I believe the signed packages resolve the issue on my end, the rest of course would need to be resolved by the the 3rd party packages you mentioned. Good luck!

**Closed by tmenier** 2022-01-22 15:29 UTC
