### ISSUE TITLE
GetJsonAsync returns null when previously used GetStringAsync

### ISSUE THREAD

**Issue by woellij** [tmenier/Flurl#638] opened 2021-07-02 07:29 UTC
Hi,

like described in https://github.com/tmenier/Flurl/issues/589 `GetJsonAsync` returns null, when previously used `GetStringAsync`.

This seems to be because `GetJsonAsync` only tries to cast the `_capturedBody` to the Type instead of checking whether it's string / byte[] and deserialize.

Our use case is, we want to log Responses in `FlurlHttp.Configure(x => x.AfterCall = async call => ...` with Response-Content-String but then cant use the same response to get the json.

**Comment by tmenier** [comment] 2021-07-09 16:06
I'm fairly sure this is a duplicate of #571, or at the very least the same fix should solve this too, but you can correct me if that's wrong. The good new is that this is at the very top of my list to fix for the next maintenance release, although I can't promise when that will be. Hopefully soon.

**Closed** 2021-07-17 17:09 UTC
Labels: bug, duplicate
