### ISSUE TITLE
Previously working integration test with HttpTest is not working after .NetCore3 update

### ISSUE THREAD

**Issue by LazloBodi** [tmenier/Flurl#493] opened 2019-12-30 16:47 UTC
We was using Flurl 2.8.2 with .NetCore2.2.
The integration test were working with TestServer and HttpTest.
After updating the project to .NetCore3.0 the flurl http client is not mocked so actual calls are made now. I've tried updating the Flurl package to 3.0.0-pre3 with the same result.

The integration tests' base constructor looks like this:

        protected IntegrationTestBase()
        {
            DbConnection = new SqliteConnection("Data Source=:memory:");
            DbConnection.Open();

            Server = new TestServer
            (
                _webHostBuilder
                    .ConfigureServices(services =>
                    {
                        services
                            .AddDbContext<DataContext>(options => options.UseSqlite(DbConnection));
                    })
                    .ConfigureAppConfiguration((context, builder) =>
                    {
                        builder.AddInMemoryCollection(_appSettings);
                    })
                    .UseStartup<TestStartup>()
                    .ConfigureTestServices(ConfigureTestServices)
            )
            {
                BaseAddress = new Uri("http://localhost:5000")
            };

            Client = Server.CreateClient();
            Context.Database.EnsureCreated();

            HttpTest = new HttpTest();
        }

**Comment by davyvanlaere** [comment] 2020-01-08 14:11
Same issue here. Upgraded from dotnet core 2.2 to 3.1. Testing does not seem to work wit the version we were using (2.4.2) and the new prerelease version (3.0.0-pre3)

**Comment by tmenier** [comment] 2020-01-08 15:06
Will investigate. @LazloBodi Why this line? `Client = Server.CreateClient();` What are you doing with the returned `HttpClient` here? Just want to make sure you're actually using Flurl to make calls.

**Comment by wimex** [comment] 2020-01-09 14:33
The issue seems to be with these lines:
```
private static readonly System.Threading.AsyncLocal<HttpTest> _test = new System.Threading.AsyncLocal<HttpTest>();
private static void SetCurrentTest(HttpTest test) => _test.Value = test;
private static HttpTest GetCurrentTest() => _test.Value;
```

Basically the AsyncLocal wrapper causes the _test variable to become NULL on async context switches, even though the HttpTest instance is created in the constructor, not in an async call (might be related to this issue: https://github.com/tmenier/Flurl/issues/375)

**Comment by wimex** [comment] 2020-01-09 15:06
> 
> 
> Will investigate. @LazloBodi Why this line? `Client = Server.CreateClient();` What are you doing with the returned `HttpClient` here? Just want to make sure you're actually using Flurl to make calls.

The quoted line creates a test client to the server which uses Flurl internally to make calls to another web service.

**Comment by davyvanlaere** [comment] 2020-01-10 09:16
A repo with reproduction of the issue:
https://github.com/davyvanlaere/FlurlIssue

I am not sure Flurl is supposed to work in this scenario, but it DID in dotnet core 2.2 ;)

**Comment by tmenier** [comment] 2020-01-10 16:03
Ah, thanks for the details. This issue was actually uncovered a while back and is due to a [change](https://github.com/aspnet/Announcements/issues/358) introduced in .NET Core 3.0. I answered a related question here:

https://stackoverflow.com/a/58440973/62600

In short, the mechanism used to flow the async call context required by `HttpTest` across the `TestServer` HTTP boundary is now disabled by default, but you can turn it on. Please try setting `TestServer.PreserveExecutionContext` to `true` and report back on whether that fixes it.

**Comment by LazloBodi** [comment] 2020-01-10 16:27
TestServer.PreserveExecutionContext solves the problem. Thanks!

**Comment by davyvanlaere** [comment] 2020-01-13 07:30
Yep, this works!

**Comment by tmenier** [comment] 2020-01-13 13:10
Great! I'll close this but hopefully it'll help others who bump into it.

**Closed by tmenier** 2020-01-13 13:10 UTC
