### ISSUE TITLE
Url.ParseInternal() loses slash separator when first path segment is uppercase

### ISSUE THREAD

**Issue by ModernRonin** [tmenier/Flurl#581] opened 2020-12-04 11:48 UTC
This happens only since upgrading to 3.0.

It's simpler to explain by means of a failing unit-test (and makes your life easier, too, probably):

```csharp
[Test]
public void Repro()
{
    var domain = "ALPHA";
    var username = "charlie";
    var left = $"https://{domain}.b2clogin.com/{domain}.onmicrosoft.com".SetQueryParam("username", username);

    var right = $"https://{domain}.b2clogin.com/".AppendPathSegments($"{domain}.onmicrosoft.com")
        .SetQueryParam("username", username);

    left.ToUri().Should().Be(right.ToUri());
}
```

If `domain` is in uppercase, as in the test, then the assertion fails because `left` is missing a slash between the host and the first path segment and `domain` has been lowercased not just in the hostname, but also in the path: `https://alpha.b2clogin.comalpha.onmicrosoft.com/?username=charlie.`

If `domain` is set to "alpha" instead, the test passes.

I debugged into it as much as was possible with sourcelink/optimized libraries and the change seems to be happening inside `Url.ParseInternal` or `Url.AppendPathSegment`. 

Considering that paths are case-sensitive, as opposed to hostnames, this would seem a rather important/urgent issue.
I noticed it because after upgrading one of my tests failed (and I like to use uppercase strings for such values in my tests because they stand out in the assertion messages).

**Comment by tmenier** [comment] 2020-12-04 13:48
Duplicate of #574?

**Comment by ModernRonin** [comment] 2020-12-09 20:58
yes, looks very much like a duplicate. Sorry.

**Closed** 2020-12-10 16:09 UTC
Labels: bug
