### ISSUE TITLE
Blazor Wasm on net5, Flurl reports Operation is not supported on this platform

### ISSUE THREAD

**Issue by WayneHiller** [tmenier/Flurl#557] opened 2020-10-03 17:19 UTC
Visual Studio: Version 16.8.0 Preview 3.2
net5: 5.0.100-rc.1.20452.10
Flurl.Http: 2.4.2

Getting this error in a Hosted Blazor Wasm on net5 site with Flurl.Http.
In the default Client project created by the Blazor Template I replaced the call to load Weather Forecasts in the FetchData.razor page

From: 
```
forecasts = await Http.GetFromJsonAsync<WeatherForecast[]>("sample-data/weather.json");
```
To 
```
forecasts = await NavMgr.BaseUri.AppendPathSegment("sample-data/weather.json").GetJsonAsync<WeatherForecast[]>();
```

Error reported in the Browser (Edge 85.0.564.68):
```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Call failed. Operation is not supported on this platform. GET http://localhost:5000/sample-data/weather.json
Flurl.Http.FlurlHttpException: Call failed. Operation is not supported on this platform. GET http://localhost:5000/sample-data/weather.json
 ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Net.Http.BrowserHttpHandler.set_AutomaticDecompression(DecompressionMethods value)
   at System.Net.Http.HttpClientHandler.set_AutomaticDecompression(DecompressionMethods value)
   at Flurl.Http.Configuration.DefaultHttpClientFactory.CreateMessageHandler()
   at Flurl.Http.FlurlClient.<.ctor>b__4_0()
   at System.Lazy`1[[System.Net.Http.HttpMessageHandler, System.Net.Http, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1[[System.Net.Http.HttpMessageHandler, System.Net.Http, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1[[System.Net.Http.HttpMessageHandler, System.Net.Http, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].CreateValue()
   at System.Lazy`1[[System.Net.Http.HttpMessageHandler, System.Net.Http, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].get_Value()
   at Flurl.Http.FlurlClient.get_HttpMessageHandler()
   at Flurl.Http.FlurlClient.CreateHttpClient()
   at System.Lazy`1[[System.Net.Http.HttpClient, System.Net.Http, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1[[System.Net.Http.HttpClient, System.Net.Http, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1[[System.Net.Http.HttpClient, System.Net.Http, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].CreateValue()
   at System.Lazy`1[[System.Net.Http.HttpClient, System.Net.Http, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].get_Value()
   at Flurl.Http.FlurlClient.GetHttpClient()
   at Flurl.Http.FlurlClient.get_HttpClient()
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   --- End of inner exception stack trace ---
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(HttpCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.HttpResponseMessageExtensions.<ReceiveJson>d__0`1[[Blazor_Wasm_Kendo_2.Client.Pages.FetchData.WeatherForecast[], Blazor_Wasm_Kendo_2.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Blazor_Wasm_Kendo_2.Client.Pages.FetchData.OnInitializedAsync() in D:\Development\Tests\Blazor Wasm Kendo 2\Client\Pages\FetchData.razor:line 50
```

Found this: https://github.com/dotnet/aspnetcore/issues/17115#issuecomment-556324814

It looks like DefaultHttpClientFactory is checking for SupportsAutomaticDecompression.

```
public virtual HttpMessageHandler CreateMessageHandler() {
			var httpClientHandler = new HttpClientHandler();

			// flurl has its own mechanisms for managing cookies and redirects

			try { httpClientHandler.UseCookies = false; }
			catch (PlatformNotSupportedException) { } // look out for WASM platforms (#543)

			if (httpClientHandler.SupportsRedirectConfiguration)
				httpClientHandler.AllowAutoRedirect = false;

			if (httpClientHandler.SupportsAutomaticDecompression) {
				// #266
				// deflate not working? see #474
				httpClientHandler.AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate;
			}
			return httpClientHandler;
		}
```

This works as a fix:

```
public class HttpClientFactoryForBlazor : DefaultHttpClientFactory
        {
            public override HttpMessageHandler CreateMessageHandler()
            {
                var httpClientHandler = new HttpClientHandler();

                // flurl has its own mechanisms for managing cookies and redirects

                try 
                { 
                    httpClientHandler.UseCookies = false; 
                }
                catch(PlatformNotSupportedException) { } // look out for WASM platforms (#543)

                if(httpClientHandler.SupportsRedirectConfiguration)
                    httpClientHandler.AllowAutoRedirect = false;

                if(httpClientHandler.SupportsAutomaticDecompression)
                {
                    // #266
                    // deflate not working? see #474
                    try
                    {
                        httpClientHandler.AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate;
                    }
                    catch(PlatformNotSupportedException) { }
                }

                return httpClientHandler;
            }
        }

public static async Task Main(string[] args)
 {
       FlurlHttp.Configure(settings =>
       {
             settings.HttpClientFactory = new HttpClientFactoryForBlazor();
       });
}
```

**Comment by tmenier** [comment] 2020-10-05 15:53
Duplicate of #542.

The code you posted from `DefaultHttpClientFactory` is actually from 3.0 and contains the fix. 2.4.2 does not check `SupportsAutomaticDecompression` (which I have to imagine would return false here), which I believe is why you encountered the bug. With 3.0 very close to full release I probably won't be fixing this in 2.x.

**Closed by tmenier** 2020-10-05 15:53 UTC
Labels: bug

**Comment by WayneHiller** [comment] 2020-10-05 18:53
Ah ok that makes sense now, was wondering why httpClientHandler.SupportsAutomaticDecompression would be returning true.
