### ISSUE TITLE
URI too long error

### ISSUE THREAD

**Issue by dcworldwide** [tmenier/Flurl#185] opened 2017-06-22 03:49 UTC
When calling PostUrlEncodedAsync I'm receiving an error when the code tries to URL encode a large string (300kb). 

```
      Invalid URI: The Uri string is too long.
System.UriFormatException: Invalid URI: The Uri string is too long.
   at System.UriHelper.EscapeString(String input, Int32 start, Int32 end, Char[] dest, Int32& destPos, Boolean isUriString, Char force1, Char force2, Char rsvd)
   at System.Uri.EscapeDataString(String stringToEscape)
   at Flurl.Url.EncodeQueryParamValue(Object value, Boolean encodeSpaceAsPlus) in C:\projects\flurl\src\Flurl.Shared\Url.cs:line 139
   at Flurl.Http.Configuration.DefaultUrlEncodedSerializer.Serialize(Object obj) in C:\projects\flurl\src\Flurl.Http.Shared\Configuration\DefaultUrlEncodedSerializer.cs:line 26
   at Flurl.Http.HttpExtensions.PostUrlEncodedAsync(IFlurlClient client, Object data, CancellationToken cancellationToken, HttpCompletionOption completionOption) in C:\projects\flurl\src\Flurl.Http.Shared\HttpExtensions.cs:line 513
```

The api we are calling is proprietary and does not accept POSTing application/json content. It only accepts a application/x-www-form-urlencoded payload.

**Comment by thiagolunardi** [comment] 2017-06-22 07:04
This is a doubt, not a issue or improve request.

Will be better if you post your question at [StackOverflow with FLURL tag](https://stackoverflow.com/questions/tagged/flurl). 

You will have faster help, and it's the proper place to do it.

**Comment by dcworldwide** [comment] 2017-06-22 10:42
I'm not doubtful. It's an issue as far as I can tell.

**Comment by thiagolunardi** [comment] 2017-06-22 12:16
Can you fork and write a test reproducing the problem?

**Comment by tmenier** [comment] 2017-06-22 13:08
Related to https://github.com/dotnet/corefx/issues/1936

**Comment by dcworldwide** [comment] 2017-06-22 23:11
No need for a repo, https://github.com/dotnet/corefx/issues/1936 explains the issue perfectly well.

**Comment by tmenier** [comment] 2017-07-16 19:28
I'd like to fix this by changing [Url.EncodeQueryParamValue](https://github.com/tmenier/Flurl/blob/master/src/Flurl.Shared/Url.cs#L138) to use `Utility.UrlEncode` instead of `Uri.EscapeDataString`, but that's not supported on all targeted platforms unfortunately. Depending on major changes under consideration for #176, we might be able to do this after that is resolved but I'm not sure yet.

**Comment by kroniak** [comment] 2017-07-20 12:45
@tmenier  Where ```WebUtilityUrlEncode``` is not supported? in PCL? We can wrap code in ```#if !PORTABLE```

**Comment by tmenier** [comment] 2017-07-21 13:00
@kroniak I believe that's what I saw, yes. I'd rather not have a PCL-only bug, but with the `netstandard` update very few platforms will get that version anymore, so that might be acceptable.

**Comment by tmenier** [comment] 2017-07-28 14:15
@kroniak .NET 4.0 is where `WebUtility.UrlEncode` is missing. I [tried](https://github.com/tmenier/Flurl/commit/137e3fbd8bc7c9e204fdbec6e37642f156fc9f31) wrapping the old implementation in `#if NET40`, but unfortunately .NET 4.5+ chooses `net40` over `netstandard`, so I think the only way to fix this for all supported platforms is to add a `net45` target to Flurl. Unless you know of another way? Thoughts?

**Comment by kroniak** [comment] 2017-07-28 15:35
@tmenier No, I dont know another way to avoid it.

**Comment by GermanKuber** [comment] 2017-11-03 23:08
I am interested in work in this issue. You would give me more information. Did you discover one way to follow?

**Comment by tmenier** [comment] 2017-11-30 16:13
This is back on my radar and I'll try to get it fixed for the next maintenance release. The best way to deal with this might be to just add a `net45` specific target to Flurl so that .NET 4.5+ takes the "else" path [here](https://github.com/tmenier/Flurl/commit/137e3fbd8bc7c9e204fdbec6e37642f156fc9f31#diff-6797c2602f9b904a3f4499bd05371125R140).

**Comment by tmenier** [comment] 2017-12-09 22:26
Fixed (except in .NET 4.0) and released.

**Comment by tmenier** [comment] 2017-12-19 16:03
This getting a re-do because as it turns out, `WebUtility.UrlEncode` is [evil](https://stackoverflow.com/a/47877559/62600).

**Comment by tmenier** [comment] 2017-12-19 21:50
An entirely different fix for this has been released. It would be great if someone could (re)test it against a very long string. https://www.nuget.org/packages/Flurl/2.6.0

**Closed by tmenier** 2017-12-19 21:50 UTC
Labels: bug
