### ISSUE TITLE
UseNewtonsoft has no effect on clientless pattern

### ISSUE THREAD

**Issue by Dreamescaper** [tmenier/Flurl#797] opened 2024-01-08 12:10 UTC
I'm using clientless pattern, and I plan to use Newtonsoft.Json as for now. Unfortunately, I cannot find a way to use Newtonsoft serializer for clientless pattern by default.

I use the following code to set the defaults:
```csharp
            FlurlHttp.Clients.WithDefaults(d =>
            {
                d.UseNewtonsoft();
            });
```

But it is not used by default, the code below still uses DefaultJsonSerializer.
```csharp
await "https://my.test/".PostJsonAsync(body);
```

Seems like the problem is that the client from FlurlHttp.Clients is assigned to FlurlRequest instance _after_ the body is serialized - and therefore NewtonsoftSerializer is not used.

I assume it also affects any other Serializer customizations.

**Comment by Dreamescaper** [comment] 2024-01-08 12:12
I was able to workaround it by adding the following line to my setup code:
```csharp
            new HttpTest().Settings.JsonSerializer = new NewtonsoftJsonSerializer();
```
But that doesn't look like an expected solution.

**Comment by tmenier** [comment] 2024-01-08 20:56
Yep, this is a pretty blatant bug. Thanks for the details, but it's actually a duplicate of #783 which I'm working on now.

**Closed by tmenier** 2024-01-08 20:56 UTC
Labels: bug, duplicate
