### ISSUE TITLE
Referenced assembly versions

### ISSUE THREAD

**Issue by jorgeyanesdiez** [tmenier/Flurl#183] opened 2017-06-14 08:18 UTC
Hi Todd,

Loving Flurl so far. I have a question about referenced assembly versions. I am not looking for support on how to fix the error itself, but rather, I am interested in knowing whether the following is normal/intended. Can you shed some light on this please?

I just upgraded my projects to Flurl.Http 1.1.2 which in turn references Flurl 2.3.0. 
When I compile my ASP.NET website (on full framework 4.5) I get the following lines.

```
No way to resolve conflict between "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes". Choosing "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.
No way to resolve conflict between "System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes". Choosing "System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.
No way to resolve conflict between "System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes". Choosing "System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.
```

I changed my build output to be a bit more vebose and found this

```
There was a conflict between "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes".
    "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" was chosen because it was primary and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes" was not.
    References which depend on "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll].
[... most of my projects ...]
    References which depend on "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes" [].
        C:\Work\root\.nuget\packages\Flurl.2.3.0\lib\portable40-net40+sl5+win8+wp8+wpa81\Flurl.dll
          Project file item includes which caused reference "C:\Work\root\.nuget\packages\Flurl.2.3.0\lib\portable40-net40+sl5+win8+wp8+wpa81\Flurl.dll".
[... my project referencing flurl.http ...]

There was a conflict between "System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes".
    "System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" was chosen because it was primary and "System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes" was not.
    References which depend on "System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll].
[... most of my projects ...]
    References which depend on "System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes" [].
        C:\Work\root\.nuget\packages\Flurl.2.3.0\lib\portable40-net40+sl5+win8+wp8+wpa81\Flurl.dll
          Project file item includes which caused reference "C:\Work\root\.nuget\packages\Flurl.2.3.0\lib\portable40-net40+sl5+win8+wp8+wpa81\Flurl.dll".
[... my project referencing flurl.http ...]

There was a conflict between "System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes".
    "System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" was chosen because it was primary and "System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes" was not.
    References which depend on "System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll].
[... most of my projects ...]
    References which depend on "System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes" [].
        C:\Work\root\.nuget\packages\Flurl.2.3.0\lib\portable40-net40+sl5+win8+wp8+wpa81\Flurl.dll
          Project file item includes which caused reference "C:\Work\root\.nuget\packages\Flurl.2.3.0\lib\portable40-net40+sl5+win8+wp8+wpa81\Flurl.dll".
[... my project referencing flurl.http ...]
```

So my question is why is the `portable40-net40+sl5+win8+wp8+wpa81\Flurl.dll` assembly referencing 2.0.5.0 instead of 4.0.0.0? is that how it's supposed to be?

EDIT: I just triple checked, and everything is building against .NET Framework v4.5. Soon I will try to migrate everything to v4.7 but in the mean time I'd appreciate some feedback on whether this is intentional or you think I am doing something wrong.

Thanks

**Comment by tmenier** [comment] 2017-07-12 14:30
@kroniak Could you investigate? I suspect [this](https://github.com/tmenier/Flurl/blob/master/src/Flurl/project.json#L24-L26) is the cause but I'm not sure I fully understand the platform compatibility implications of just changing it.

**Comment by kroniak** [comment] 2017-07-16 09:51
@tmenier I have delete it in vs2017 version. Wait for PR.

**Comment by jorgeyanesdiez** [comment] 2017-07-16 13:24
Thanks a lot for all your hard work

**Comment by tmenier** [comment] 2017-07-18 03:58
@jorgeyanesdiez Fix for this in pre-release. Please test and report your findings.

`PM> Install-Package Flurl.Http -Pre`

**Comment by jorgeyanesdiez** [comment] 2017-07-18 10:39
I'm on holidays for a few days, but I promise to fully test when I come back.
I just did some quick tests and the reference warnings seem to be gone for .NET 4.5 Full framework projects. I'll upgrade to the pre version everywhere and let you know what happens early next week.

On a side note, I have a tiny project that extends Flurl.Http IFlurlClient that targets both .NET Standard 1.4 and .NET 4.5. I had to add the following to make it work:

        <ItemGroup Condition="'$(TargetFramework)'=='net45'">
          <PackageReference Include="System.Net.Http" Version="4.3.2" />
        </ItemGroup>

But that seems very reasonable since `HttpExtensions` uses `HttpCompletionOption`.

**Comment by kroniak** [comment] 2017-07-18 10:53
@jorgeyanesdiez You had add system reference to net45, not package. You deleted it in upgrading process.

Look at #176 thread.

```xml
  <ItemGroup Condition="'$(TargetFramework)' == 'net45'">
    <Reference Include="System.Net.Http" />
  </ItemGroup>
```

**Comment by jorgeyanesdiez** [comment] 2017-07-18 11:26
@kroniak you are absolutely right, I messed up because I usually do this for netstandard and not the other way around. Thanks.

**Comment by tmenier** [comment] 2017-07-21 03:51
Full release is published

**Closed by tmenier** 2017-07-21 03:51 UTC
Labels: ready

**Comment by jorgeyanesdiez** [comment] 2017-07-24 12:42
I can confirm the warning messages are gone in all my products, and all seems to be working great. However, I had to add the fragment mentioned above by @kroniak to all my projects referencing Flurl.Http under net45 because `System.Net.Http` is required by `HttpExtensions` but it doesn't seem to be included for this target.
