### ISSUE TITLE
Error when using cookies with Path

### ISSUE THREAD

**Issue by Meberem** [tmenier/Flurl#496] opened 2020-01-30 15:15 UTC
I think this may be an issue with the Cookie Container itself rather than Flurl. Basically when there is a cookie set with a path I get a FlurlHttpException when making subsequent calls. The api I am using does some very strange things with cookies but this can be demonstrated by the following

```
var fc = new FlurlClient().EnableCookies();
var response1 = await fc.Request("https://www.google.com").GetAsync();

fc.Cookies.Add("test", new Cookie("test-cookie", "Test Value", "/Something", "www.google.com")); // Essentially what the first response would set

var response2 = await fc.Request("https://www.google.com").GetAsync();

----------
FlurlHttpException
Call failed. The 'Path'='/Something' part of the cookie is invalid. GET https://www.google.com

```

![image](https://user-images.githubusercontent.com/441023/73462326-ea599800-437b-11ea-8109-feff1b425638.png)

**Comment by tmenier** [comment] 2020-02-02 15:22
Not a bug. It's saying that what you're doing is invalid, which it is.

According to the [spec](https://tools.ietf.org/html/rfc6265#section-4.1.2.4):

> The user agent will include the cookie in an HTTP request only if the path portion of the request-uri matches (or is a subdirectory of) the cookie's Path attribute, where the %x2F ("/") character is interpreted as a directory separator.

You're sending a path that isn't part of the request URI.

**Comment by Meberem** [comment] 2020-02-02 16:29
Thank you for your response, if I may clarify my situation: I am being forced to use an API that, to put it nicely, is not modern...

- I login by calling `GET /Something/login`, Flurl receives a number of cookies one of which has a path `/Something` the rest have the default path `/`.
- Any calls to `/Something/next-operation` are fine.
- Calls to `/other-operation` result in the above error.

As I don't have control over the API how should I go about removing invalid cookies from the request? I have a rudimentary approach here:

```
request.ConfigureRequest(a =>
{
    a.BeforeCall = call =>
    {
        var path = call.FlurlRequest.Url.ToUri().AbsolutePath;
        foreach (var (name, cookie) in call.FlurlRequest.Cookies.ToArray())
        {
            if (!path.StartsWith(cookie.Path))
            {
                call.FlurlRequest.Cookies.Remove(name);
                }
            }
        }
    }
});                       
```

It looks like this [dotnet issue](https://github.com/dotnet/runtime/issues/26141) will fix a number of Path related issues with cookies and I do appreciate that it is not the responsibility of Flurl to deal with bad APIs

**Comment by tmenier** [comment] 2020-02-02 18:17
Thanks for clarifying. I'll keep this open for possible consideration.

**Comment by timh52280** [comment] 2020-02-03 02:33
This same problem has been happening to me, in several sites have web systems with this type of cookies and currently flurl can not handle them so I think this request should be taken into consideration.

[https://i.imgur.com/UDcmmni.png](url)

**Comment by timh52280** [comment] 2020-02-04 15:56
@Meberem I tried your PR but does not work very well, that it worked for me is https://github.com/tmenier/Flurl/issues/296#issuecomment-492497935

**Comment by Meberem** [comment] 2020-02-04 16:46
@timh52280 I'm not quite sure what the differences would be between the comment and the PR I created. Would you be able to add/update the tests in my PR with the issues you are seeing?

**Comment by tmenier** [comment] 2020-02-08 19:03
Cookies are getting a major overhaul in 3.0. I'll make sure this issue gets addressed.

**Comment by tmenier** [comment] 2020-03-24 18:31
@Meberem @timh52280 I've detailed my plan for cookies in 3.0 in #506. Please have a look and leave any feedback you might have. It doesn't address this issue specifically (I'll still be looking into this), but I'd like to gather as much feedback as possible from people who need to interact with cookies in general.

**Comment by timh52280** [comment] 2020-03-24 19:59
@tmenier  Okay sir I'll try it and go back with some feedback, thanks for you support.

**Comment by johnwc** [comment] 2020-03-24 21:38
@Meberem The difference in the code in the comment, is that it does not just simply through away the cookie if it throws an exception. The issue was not with the path, the issue was that the domain in the uri parameter had a . at the beginning of it. And that was causing the .Net code to choke. By calling the same method without the uri parameter, the cookie gets added.

**Comment by tmenier** [comment] 2020-08-08 16:34
@Meberem @timh52280 @johnwc #506 (massive overhaul of cookies) is now available in the latest prerelease. `CookieContainer` is bypassed entirely and I'm pretty sure this is resolved in the new implementation, but I would highly encourage you to test.

**Closed** 2020-11-01 18:03 UTC
Labels: 3.0
