### ISSUE TITLE
.NET 4.6.2 target

### ISSUE THREAD

**Issue by steve-torchia** [tmenier/Flurl#156] opened 2016-12-20 18:16 UTC
Would it be a lot of effort to target .NET 4.6.2?   I could fork and give it a shot if pointed in the right direction.

**Comment by tmenier** [comment] 2016-12-21 00:16
@kroniak thoughts?

**Comment by kroniak** [comment] 2016-12-21 13:27
@steve-torchia @tmenier There are any problem with net 4.6.2? It supported by net std.

**Comment by steve-torchia** [comment] 2016-12-21 17:37
@kroniak @tmenier  perhaps not specifically a 4.6.2 problem.   I have an asp.net core app targeting 4.6.2 and it's looking for System.Diagnostics.DiagnosticSource 4.0.0   The package I have is 4.3.0

> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55155/api/values
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method DataFeedManager.Controllers.ValuesController.GetAsync (DataFeedMgr) with arguments ((null)) - ModelState is Valid
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action DataFeedManager.Controllers.ValuesController.GetAsync (DataFeedMgr) in 4136.7709ms
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
Flurl.Http.FlurlHttpException: Request to http://<snip> failed. Could not load file or assembly **'System.Diagnostics.DiagnosticSource, Version=4.0.0.0,** Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Net.Http.WinHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Flurl.Http.Configuration.FlurlMessageHandler.<SendAsync>d__1.MoveNext()

**Comment by kroniak** [comment] 2016-12-22 08:07
@steve-torchia I cant reproduce this issue

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Flurl.Http": "1.1.1",
    "System.Diagnostics.DiagnosticSource": "4.3.0" 
  },

  "frameworks": {
    "net462": {

    }
  }
}
```

```c#
public class Program
    {
        public static void Main(string[] args)
        {
			Task.Run(async () =>
			{
				var getResp = await "http://api.foo.com".GetAsync();
			}).Wait();

		}
    }
```

**Comment by steve-torchia** [comment] 2016-12-22 19:15
@kroniak  I think this is a problem with VS2017 and it's rough-around-the-edges tooling.   I'm going to try in VS2015 and report back

**Comment by tmenier** [comment] 2017-01-25 15:45
Anything to report? Considering closing this issue but wanted to give you a chance report any new findings.

**Comment by steve-torchia** [comment] 2017-01-25 18:26
Oh man I'm sorry I forgot to report back.  Once I went to VS2015 this problem went away.  I think this is related to the tooling issues in VS2017.   

At some point I will try a migration from my VS15 solution to VS17 to see if that "fixes" it.   If you close this out and I find any more relevant information I could just post back here and reopen?

**Comment by tmenier** [comment] 2017-01-25 18:39
Yup, works for me. No problem!

**Closed by tmenier** 2017-01-25 18:39 UTC
Labels: question

**Comment by anmelegov** [comment] 2019-08-20 11:47
And what is the solution? I've faced the same problem

**Comment by kroniak** [comment] 2019-08-21 06:32
@anmelegov what case do you have? Please give us some example
