### ISSUE TITLE
Posting multipart/form-data content replaces header with content-type header from the client

### ISSUE THREAD

**Issue by Pyrobolser** [tmenier/Flurl#592] opened 2021-01-23 00:26 UTC
When using Flurl, I reuse the same client created from a `FlurlClientFactoryBase` when using the same BaseUrl.
I set this client "Content-Type" header to be "application/json" as this is the most common Content-Type for every request but one for file upload using "multipart/form-data".

When using `IFlurlRequest.PostMultipartAsync(...)` or `IFlurlRequest.PostAsync(CapturedMultipartContent mp)` the actual request content header "Content-Type" is using "application/json". But if I remove the client "Content-Type" header beforehand, the content header "Content-Type" is properly using "multipart/form-data" with the correct "boundary".

Test code
```cs
FlurlClient client = new FlurlClient("http://randomwebsite.url");

client.BeforeCall(act =>
{
    Console.WriteLine(act.HttpRequestMessage.Content.Headers.ToString());
});

// Comment/Uncomment the line below to change the behavior
client.Headers.Add("Content-Type", "application/json");

var mp = new CapturedMultipartContent();
mp.AddString("hello", "world")
    .AddString("more", "text");

IFlurlRequest request = client.Request("Random", "Url");
            
try
{
    await request.PostAsync(mp);
}
catch(FlurlHttpException ex)
{

}

try
{
    await request.PostMultipartAsync(mp => mp.AddString("hello", "world")
                                                .AddString("more", "text"));
}
catch (FlurlHttpException ex)
{

}
```

Right now, as a workaround, I am removing/adding again the Content-Type from the client before/after that request but that doesn't seem like a good solution. Am I doing something wrong? Should I use a separate client for multipart/form-data?
Thanks a lot for your work on this library it's been really easy to work with so far!

**Comment by tmenier** [comment] 2021-01-26 17:29
If I'm understanding you correctly, then this is expected behavior. The order of precedence for a header like Content-Type is:

explicitly set on FlurlRequest > explicitly set on FlurlClient > some reasonable default

In this case, what you've set at the client level is overwriting the reasonable default of multipart/form-data. 2 possible solutions, and I recommend them in this order:

1. Do you really need to set application/json on the client? I understand that's what you want most of the time, but if you're using methods like `PostJsonAsync`, that's already getting set, i.e. application/json _is_ the reasonable default with those methods.

2. If this above does not apply, maybe because for whatever reason you need to use `PostAsync` or `PostStringAsync` for your JSON calls, then I'd recommend doing `request.WithHeader("Content-Type", "multipart/form-data").PostMultipartAsync` when you do file uploads.

Or, your idea of separate client is probably just fine too if it's the most convenient. You run into socket exhaustion problems at thousands of clients, not 2. :)

**Comment by Pyrobolser** [comment] 2021-01-29 17:28
Thank you for your answer.

I will try and go with 1. which does make sense.
If I want to go with 2. I would have to add myself the _boundary_ part, I tried adding a random GUID and for some reason it didn't work very well but 1. should suit my needs!

Cheers!

**Comment by tmenier** [comment] 2021-01-30 16:39
Sounds great. I don't think there's a bug here, and I think it would be a very rare case that someone would need to go with option 2, so I'm going to close this.

**Closed by tmenier** 2021-01-30 16:39 UTC
Labels: bug
