### ISSUE TITLE
Url.ToString gives back wrong result causing cookies to not be saved in the CookieJar

### ISSUE THREAD

**Issue by AeonLucid** [tmenier/Flurl#585] opened 2020-12-12 23:12 UTC
This issue causes cookies to be saved incorrectly. I tried to write a test to reproduce the issue but `CookieCutter.IsValid` calls `Url.IsValid` which calls `Url.ToString()` implicitly.

Here is a test which reproduces this issue.
```csharp
[Test]
public async Task TestCookies()
{
    HttpTest.RespondWith("hi", cookies: new { x = "bar" });

    var client = new FlurlClient();
    var jar = new CookieJar();
    var response = await "https://cookies.com/"
        .WithClient(client)
        .WithCookies(jar)
        .SetQueryParams(new QueryParamCollection
        {
            {"a", "b c"},
            {"c", "d"},
        })
        .GetAsync();

    Assert.IsNotEmpty(response.Cookies);
    Assert.AreEqual("bar", response.Cookies.FirstOrDefault(c => c.Name == "x")?.Value);
    Assert.IsNotEmpty(jar);
    Assert.AreEqual("bar", response.Cookies.FirstOrDefault(c => c.Name == "x")?.Value);
}
```

It fails inside CookieCutter.IsValid where `Url.IsValid` is called. Passes this url into `Url.IsValid`.

![image](https://user-images.githubusercontent.com/4643257/101998854-33d27d80-3cd7-11eb-9fc3-05cecb9cce97.png)

Funny thing is, if you open the `OriginUrl` before `Url.IsValid` debug view before the method is called like so

![image](https://user-images.githubusercontent.com/4643257/101998816-da6a4e80-3cd6-11eb-8126-47fae83ee8d4.png)

Then the correct url is passed into `Url.IsValid`.

![image](https://user-images.githubusercontent.com/4643257/101998876-72683800-3cd7-11eb-8e6a-786f80e3b83a.png)

I think this is because it loads all the properties and calls `EnsureParsed` in the background.

**Comment by tmenier** [comment] 2020-12-14 03:13
This is legit. Thanks for reporting.

**Comment by tmenier** [comment] 2020-12-14 04:52
Yep, this is legit. And I learned something new. The root of the problem is in `FlurlResponse.LoadCookies`. It needs the URL of the original request in order to parse the cookies and gets it via `HttpResponseMessage.RequestMessage.RequestUri.ToString()`. But apparently `Uri.ToString()` un-encodes query params, effectively giving you an invalid URI in this case because there's a space in it, even though it was property encoded when the request was sent! Switched from `ToString()` to `AbsoluteUri` and it works as expected. Thanks for reporting.

**Comment by tmenier** [comment] 2020-12-14 21:03
Fixed & released in 3.0.1

**Closed by tmenier** 2020-12-14 21:03 UTC
Labels: bug
